name: test-ecs
on:
    push:
        branches: [main]
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: docker-hub login
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        